from pathlib import Path
from typing import Any

class FileDataError(Exception):
    pass

class Page:
    def get_text(self, option: str, sort: bool = ...) -> str: ...

class Document:
    is_encrypted: bool
    metadata: dict[str, Any]

    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Page: ...
    def close(self) -> None: ...
    def get_toc(self) -> list[tuple[int, str, int]]: ...
    def xref_length(self) -> int: ...

def open(file: Path | str | bytes | bytearray | memoryview) -> Document: ...
